title = "Regras Gitleaks personalizadas"
description = "Detecta chaves AWS, Azure, JWT, SSH, criptografia e variáveis sensíveis"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''

[[rules]]
id = "azure-client-secret"
description = "Azure Client Secret"
regex = '''(?i)azure(.{0,20})?(?-i)['\"][0-9a-zA-Z\-\._]{32,}['\"]'''

[[rules]]
id = "generic-api-key"
description = "Chave API genérica"
regex = '''(?i)(api key|apikey|token)(.{0,10})?[:=]\s*['"][0-9A-Za-z\-_]{16,}['"]'''

[[rules]]
id = "jwt-token"
description = "JSON Web Token"
regex = '''eyJ[A-Za-z0-9\-_=]+\.eyJ[A-Za-z0-9\-_=]+\.?[A-Za-z0-9\-_.+/=]*'''

[[rules]]
id = "ssh-private-key"
description = "Chave SSH privada"
regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''

[[rules]]
id = "rsa-private-key"
description = "Chave RSA privada"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''

[[rules]]
id = "pgp-private-key"
description = "Chave PGP privada"
regex = '''-----BEGIN PGP PRIVATE KEY BLOCK-----'''

[[rules]]
id = "dotenv"
description = "Variáveis .env"
path = '''\.env''' 
regex = '''.'''
entropy = 4.5

[[rules]]
id = "high-entropy"
description = "Strings de alta entropia"
regex = '''[A-Za-z0-9+/=]{40,}'''
entropy = 4.5