name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências Node.js
        run: |
          # Garante package-lock.json e node_modules
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Executar OWASP Dependency-Check
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            owasp/dependency-check:12.1.0 \
            --scan /src \
            --format JSON \
            --out /src \
            --disableArchive

      - name: Validar relatório e listar vulnerabilidades
        run: |
          REPORT="dependency-check-report.json"
          # Conta dependências com vulnerabilidades
          vuln_count=$(jq '[.dependencies[] | select(.vulnerabilities != null)] | length' "$REPORT")
          if [ "$vuln_count" -eq 0 ]; then
            echo "✅ Nenhuma vulnerabilidade encontrada pelo Dependency-Check"
          else
            echo "❌ Encontradas $vuln_count dependências vulneráveis:"
            jq -r '
              .dependencies[]
              | select(.vulnerabilities != null)
              | "\(.fileName):\n  \(.vulnerabilities[]
                  | "- [\(.severity)] \(.name): \(.description)"
                )"
            ' "$REPORT"
            exit 1
          fi
