name: OWASP Retire.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  retirejs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Retire.js
        run: npm install -g retire

      - name: Executar Retire.js scan
        run: retire --outputformat json --outputpath retire-report.json

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validar resultados
        run: |
          issues=$(jq '.data | length' retire-report.json)
          if [ "$issues" -eq 0 ]; then
            echo "✅ Nenhuma vulnerabilidade encontrada pelo Retire.js"
          else
            echo "❌ Retire.js encontrou $issues problemas:"
            jq -r '.data[]
                    | "\(.component)@\(.version):
                       \(.vulnerabilities[]
                         | "- \(.info[0]) (categoria: \(.severity))")"' \
                 retire-report.json
            exit 1
          fi

      - name: Upload Retire.js report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: retirejs-report
          path: retire-report.json
