name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    name: SonarQube Scanner & Quality Gate
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v20
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          PROJECT_KEY:    ${{ secrets.PROJECT_KEY }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$PROJECT_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - id: parse_task
        name: Parse report-task.txt
        run: |
          # Extrai analysisId do relatório local
          echo "analysis_id=$(grep analysisId .scannerwork/report-task.txt | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Validate Quality Gate
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -s -u "${SONAR_TOKEN}:" \
            "${SONAR_HOST_URL}/api/qualitygates/project_status?analysisId=${{ steps.parse_task.outputs.analysis_id }}" \
            | tee qg.json
          status=$(jq -r .projectStatus.status qg.json)
          echo "Quality Gate status: $status"
          if [ "$status" != "OK" ]; then
            echo "❌ Quality Gate FAILED"
            jq -r '.projectStatus.conditions[]
                   | "\(.status) em métrica \(.metricKey): valor \(.actualValue)/\(.errorThreshold)"' qg.json
            exit 1
          else
            echo "✅ Quality Gate PASSED"
          fi

      - name: Upload SonarQube report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-qg-report
          path: qg.json
